name: linux

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:

  build-linux-release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt -yq update
          sudo apt -yq install \
              build-essential cmake git zip \
              libcurl4-openssl-dev libtinyxml2-dev \
              libminizip-dev zlib1g-dev

      - name: Configure
        run: |
          cd $GITHUB_WORKSPACE
          mkdir cmake-build && cd cmake-build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release \
            -DPLATFORM_LINUX=ON -DBUILD_SSCRAP=ON \
            -DSS_DEV_ID=${{ secrets.SS_DEV_ID }} -DSS_DEV_PWD=${{ secrets.SS_DEV_PWD }} \
            ..

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/cmake-build
          make sscrap-utility-release
          mv sscrap-*.zip $GITHUB_WORKSPACE

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'sscrap-*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}